[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.16"
aws-sdk-dynamodb = { workspace = true }
aws-sdk-secretsmanager = { workspace = true }
chrono = { workspace = true }
cuid2 = "0.1.3"
lambda_http = { workspace = true }
reqwest = { workspace = true }
scraper = "0.27"
serde = { workspace = true }
serde_json = { workspace = true }
serde_dynamo = { workspace = true }
thiserror = { workspace = true }
url = "2.5.4"
